products=[
    {'_id':'1',
      'name': '',
      'description': '',
      'photo': '/images/ARMY_BOOM.jpg',
      'rating': 5.0,
      'numrating': 100,
      'price':30,
      'countInStock': 10,
      'category': '',
    },
    {'_id':'2',
    'name': 'BE Deluxe Edition',
    'description': 'BE Deluxe Edition physical version',
    'photo': '/images/BE_Deluxe_Edition.jpg',
    'rating': 5.0,
    'numrating': 1000,
    'price':35,
    'countInStock': 0,
    'category': 'accessories',
    },
    {'_id':'3',
    'name': 'BT21 Doll',
    'description': 'New collection',
    'photo': '/images/BT21_doll.jpg',
    'rating': 4.0,
    'numrating': 150,
    'price':15,
    'countInStock': 300,
    'category': 'accessories',
    },
    {'_id':'4',
    'name': 'BT21 Key Clip',
    'description': 'New product collection',
    'photo': '/images/BT21_key_clip.jpg',
    'rating': 4.3,
    'numrating': 72,
    'price':3,
    'countInStock': 100,
    'category': 'accessories',
    },
    {'_id':'5',
    'name': 'Concept T-Shirt',
    'description': 'good quality t shirt',
    'photo': '/images/concept_T_shirt.jpg',
    'rating': 4.5,
    'numrating': 30,
    'price':10,
    'countInStock': 11,
    'category': 'accessories',
    },
    {'_id':'6',
    'name': 'Wings',
    'description': 'Physical Album',
    'photo': '/images/wings.jpg',
    'rating': 4.9,
    'numrating': 1200,
    'price':35,
    'countInStock': 0,
    'category': 'accessories',
    },
    {'_id':'7',
    'name': 'MOTS7',
    'description': 'Physical Album of Map of the soul 7',
    'photo': '/images/MAP-OF-THE-SOUL-7.jpg',
    'rating': 5.0,
    'numrating': 1500,
    'price':45,
    'countInStock': 0,
    'category': 'accessories',
    },
    {'_id':'8',
    'name': '2cool4skool',
    'description': 'Physical Album of 2cool4skool',
    '': '/images/2cool4skoolalbumcover.jpg',
    'rating': 4.5,
    'numrating': 1000,
    '':25,
    '': 20,
    'category': 'accessories',
    },
]

