const products=[
    {'_id':'1',
      'name': 'A.R.M.Y. BOOM',
      'description': 'this is the latest version of ARMY BOOM',
      'photo': '/images/ARMY BOOM.jpg',
      'rating': 5.0,
      'numrating': 100,
      'price':30,
      'category': 'accessories',
    },
    {'_id':'2',
    'name': 'BE Deluxe Edition',
    'description': 'BE Deluxe Edition physical version',
    'photo': '/images/BE_Deluxe_Edition.jpg',
    'rating': 5.0,
    'numrating': 1000,
    'price':35,
    'category': 'accessories',
    },
    {'_id':'3',
    'name': 'BT21 Doll',
    'description': 'New collection',
    'photo': '/images/BT21 doll.jpg',
    'rating': 4.0,
    'numrating': 150,
    'price':15,
    'category': 'accessories',
    },
    {'_id':'4',
    'name': 'BT21 Key Clip',
    'description': 'New product collection',
    'photo': '/images/BT21 key clip.jpg',
    'rating': 4.3,
    'numrating': 72,
    'price':3,
    'category': 'accessories',
    },
    {'_id':'5',
    'name': 'Concept T-Shirt',
    'description': 'good quality t shirt',
    'photo': '/images/concept T-shirt.jpg',
    'rating': 4.5,
    'numrating': 30,
    'price':10,
    'category': 'accessories',
    },
    {'_id':'6',
    'name': 'Wings',
    'description': 'Physical Album',
    'photo': '/images/wings.jpg',
    'rating': 5.0,
    'numrating': 1200,
    'price':35,
    'category': 'accessories',
    },
]

export default products
